#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
range = list(range(1, 11))
total = 0
for i in range:
    print(i)


# code for sum of even-valued terms:

# if i % 2 == 0 :
#   i = i