def split_by_index(ctext: str, n: int) -> int:
    ctext = ctext.replace(" ", "")
    ctext.upper()

    return ctext[::n] 
def prime_factors(n):
    i = 2
    factors = []
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors
def remove_consecutive_indexes(input: str, start: int, end: int) -> str:
        cipher_text_list = list(input)
        for i in range((end - start) + 1):
            del cipher_text_list[start - 1::start]

        finallist = ''.join(cipher_text_list)
        return finallist
def split_string_every_n_blocks(input_string: str, blocklength: int) -> list:
    blocklength = int(blocklength)
    ciphertext = input_string
    list_out = []
    rangeofexecution = len(input_string) / blocklength
    rangeofexecution = int(rangeofexecution)
    
    for i in range(rangeofexecution):
        new_block = ciphertext[:blocklength]
        list_out.append(new_block)
        ciphertext = ciphertext.replace(new_block, '', 1)
        
    return list_out    


ctextin = "OUEVEBEKCOAAFEOITIBEHIAKUTNOTQDRHKRITEIHAEGOJARSHNTTEESTAOMOSEODUEDTWMGTCWOCCWDETFAEIEHIOICIATCHFLNNOKNIATVIOUADTUAATTROAHWNFASHLDIIESETTTLROMWTFIEAOYALARMYAHUHAKKWINLDTENNKYLDTABWWNOIONIRISHBAHOGNMNUKLKEEGTSEIEATRHIGLTENSDARFHAILWNIEWDBIBNRATUNFANTCYRHEAERASTMTHUCASEVGSIMOSIEETEDMEORGDONESBPTMETREUAAVTCWATNEDTENOUTTTEFETEHEEWATMTHRTBEHAAYSABANTWORDABSALSNYPIIBNASYWLEKSDTATTOEEOSHTSHETLLEAWATWHEOOVIFDBNOTUSOAEWHLEUVNETEAAODMRUDYHNREHNVRETATGHDAHTHEEORSONOREUEBEPIIDTNZSHSLEERPHNCDLOHOGOHUOTATAVTGFWDDATUIDENNEHHIATTCRIHNOEDWODVTLDNNDSBAIAIEIOILNTEMIRYTTEYTSTHIRKWCUTLBHSEBADNTAERTIEAEAEWDACNAKSEUTEBAABAETTSTDMHTTARFYNYHNEFHSGEYUSSOSLNINEIADARAWWHIADODKTRZCUANITIEUHAETSNOTAIONOTADLRROEFIFDAMOTHETAONRUIALTYEDLHUXTELLNTTWTWSGVBEHOTIAIEOAFAOEAEOFNSCHNLEBNFSDTTENFHGOORAEEMTDTECOVNDTKXTOAIFOAUREDOMNSEIITSUIRPBIEDAYTCHHLNRUANNWBHTITKOEUOTWGWTRHDSTSQIMEAHASEELKRISUNIIITAATDHSHINHERWHONPLEKTDAERODIEPDAFETLETPIRGIICCGYTEEAENRINNHTICISCSRNANNHEALLTCHIEOFDILEMOYEKEHDRSIBNILSETATDPEWNDRVHFAEEERNLHERNEIYTTDTDYSOIEUETOAUAFIAHIDDHGNTYNNTNTGEFILOTTWOTEPHNLWIVERWKHARTGEDTHENEOONADBHOUOTEEETNEHKLRNOADNNHITBAEOTEGTNTMGTIHKAEEICNIDOMXEILOOEETDLTPYAPDSHDFNEATARFCITBRUETSEEIDUINHBELTLGALFCMIATAOOEIDTSGKDHEHTCEDTISAHIIPJBEOOAWOUIUONNNWWTCUTSUROAMTKOOOHTIHHLRMBDIEDYUOEAAMOSYNESDLIHITTETRTEGTEAESBLHELSKSNSIJOLNAAWSSTEGSTUSEADMGATINIEESPBTMHOTIWADDTEASTAATHLAHLGSETNALEPDADNISULENUGWVAWTDNORLIOCCHNENAOTISICSIMTEHADGKAFMIONAERINTGTESOTHOOIIRHA"

banana = split_string_every_n_blocks(ctextin, 287)

print(f"{len(ctextin)} {prime_factors(len(ctextin))}")






