from mission8 import *

ctextin = "OUEVEBEKCOAAFEOITIBEHIAKUTNOTQDRHKRITEIHAEGOJARSHNTTEESTAOMOSEODUEDTWMGTCWOCCWDETFAEIEHIOICIATCHFLNNOKNIATVIOUADTUAATTROAHWNFASHLDIIESETTTLROMWTFIEAOYALARMYAHUHAKKWINLDTENNKYLDTABWWNOIONIRISHBAHOGNMNUKLKEEGTSEIEATRHIGLTENSDARFHAILWNIEWDBIBNRATUNFANTCYRHEAERASTMTHUCASEVGSIMOSIEETEDMEORGDONESBPTMETREUAAVTCWATNEDTENOUTTTEFETEHEEWATMTHRTBEHAAYSABANTWORDABSALSNYPIIBNASYWLEKSDTATTOEEOSHTSHETLLEAWATWHEOOVIFDBNOTUSOAEWHLEUVNETEAAODMRUDYHNREHNVRETATGHDAHTHEEORSONOREUEBEPIIDTNZSHSLEERPHNCDLOHOGOHUOTATAVTGFWDDATUIDENNEHHIATTCRIHNOEDWODVTLDNNDSBAIAIEIOILNTEMIRYTTEYTSTHIRKWCUTLBHSEBADNTAERTIEAEAEWDACNAKSEUTEBAABAETTSTDMHTTARFYNYHNEFHSGEYUSSOSLNINEIADARAWWHIADODKTRZCUANITIEUHAETSNOTAIONOTADLRROEFIFDAMOTHETAONRUIALTYEDLHUXTELLNTTWTWSGVBEHOTIAIEOAFAOEAEOFNSCHNLEBNFSDTTENFHGOORAEEMTDTECOVNDTKXTOAIFOAUREDOMNSEIITSUIRPBIEDAYTCHHLNRUANNWBHTITKOEUOTWGWTRHDSTSQIMEAHASEELKRISUNIIITAATDHSHINHERWHONPLEKTDAERODIEPDAFETLETPIRGIICCGYTEEAENRINNHTICISCSRNANNHEALLTCHIEOFDILEMOYEKEHDRSIBNILSETATDPEWNDRVHFAEEERNLHERNEIYTTDTDYSOIEUETOAUAFIAHIDDHGNTYNNTNTGEFILOTTWOTEPHNLWIVERWKHARTGEDTHENEOONADBHOUOTEEETNEHKLRNOADNNHITBAEOTEGTNTMGTIHKAEEICNIDOMXEILOOEETDLTPYAPDSHDFNEATARFCITBRUETSEEIDUINHBELTLGALFCMIATAOOEIDTSGKDHEHTCEDTISAHIIPJBEOOAWOUIUONNNWWTCUTSUROAMTKOOOHTIHHLRMBDIEDYUOEAAMOSYNESDLIHITTETRTEGTEAESBLHELSKSNSIJOLNAAWSSTEGSTUSEADMGATINIEESPBTMHOTIWADDTEASTAATHLAHLGSETNALEPDADNISULENUGWVAWTDNORLIOCCHNENAOTISICSIMTEHADGKAFMIONAERINTGTESOTHOOIIRHA"

split_list = split_string_every_n_blocks(ctextin, 7)

ioc_english_text = 0.0686
ioc_random = 0.0385

msg1 = "This text seems to be encoded with a transposition cipher or a monoalpabetic substitution cipher\n"
msg2 = "This text seems to be encoded with a polyalphabetic cipher\n"
for thing in split_list:
    
    current_ioc = ioc(thing)
    
    if current_ioc > ioc_random and current_ioc < ioc_english_text:
        if (ioc_english_text - current_ioc) > (current_ioc - ioc_random):
            print(f"Ioc is {round(current_ioc, 5)}{msg1}")
        else:
            print(f"Ioc is {round(current_ioc, 5)}{msg2}")
            
    else: 
        print(f"Ioc is {current_ioc}, please check that this is correct")
        
